# Generated by Django 5.2.13 on 2026-05-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mockendpoint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mockendpoint',
            unique_together={('user_id', 'url_path', 'method')},
        ),
    ]
