# Generated by Django 5.2.13 on 2026-05-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_webhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockWebSocketEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('url_path', models.CharField(max_length=255)),
                ('on_connect_message', models.JSONField(blank=True, default=dict, null=True)),
                ('echo_mode', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('user_id', 'url_path')},
            },
        ),
    ]
