# Generated by Django 5.2.13 on 2026-05-06 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mockwebsocketendpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockAPI',
        ),
        migrations.AddField(
            model_name='mockendpoint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mockendpoint',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('CONNECT', 'CONNECT')], default='GET', max_length=10),
        ),
    ]
